// src/components/TabSearch.vue
<template>
  <div :class="bem( `tab-search`, { theme } )">
    <label class="tab-search__label">
      <svg class="tab-search__icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
        <path d="M15.707 14.293l-4.822-4.822a6.019 6.019 0 1 0-1.414 1.414l4.822 4.822a1 1 0 0 0 1.414-1.414zM6 10a4 4 0 1 1 4-4 4 4 0 0 1-4 4z"></path>
      </svg>
      <input class="tab-search__input" type="search" v-model="search_text" @input="onUpdateSearchText" :placeholder="__MSG_tab_search_placeholder__"/>
      <svg class="tab-search__clear-icon" @click="clearSearchText()" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
        <path fill-rule="evenodd" d="M6.586 8l-2.293 2.293a1 1 0 0 0 1.414 1.414L8 9.414l2.293 2.293a1 1 0 0 0 1.414-1.414L9.414 8l2.293-2.293a1 1 0 1 0-1.414-1.414L8 6.586 5.707 4.293a1 1 0 0 0-1.414 1.414L6.586 8zM8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0z"></path>
      </svg>
    </label>
  </div>
</template>

<script>
import {
  getWindow,
} from "../store/helpers.mjs"
import {
  bem,
  debounce,
  onStateChange,
} from "./helpers.mjs"

export default {
  name: "tab-search",
  props: [ "theme" ],
  data() {
    return {
      search_text: "",
      search_resolved: true,
      window_id: window.current_window_id,
      search_history: []
    }
  },
  computed: {
    __MSG_tab_search_placeholder__() {
      return window.background.getMessage( "tab_search_placeholder" )
    }
  },
  created() {
    onStateChange( state => {
      const state_window = getWindow( state, this.window_id )
      if( state_window && state_window.search != null ) {
        const index = this.search_history.indexOf( state_window.search.text )
        if( index > -1 ) {
          this.search_history.splice( index, 1 )
        } else {
          this.search_text = state_window.search.text
        }
        this.search_resolved = state_window.search.resolved
      } else {
        this.search_text = ""
        this.search_resolved = true
      }
    })
  },
  methods: {
    bem,
    onUpdateSearchText: debounce( function() {
      console.info('runSearch', this.search_text)
      this.search_history.push( this.search_text )
      window.background.runTabSearch( window.store, this.window_id, this.search_text )
    }, 250 ),
    clearSearchText() {
      console.info('clearSearchText', this.search_text)
      this.search_text = ""
      window.background.runTabSearch( window.store, this.window_id, this.search_text )
    },
  }
}
</script>

<style lang="scss">
@import "../styles/photon";

$dark-awesome-bar-background: #474749;

%tab-search__icon {
  position: absolute;
  top: 11px;
  height: 16px;
  width: 16px;
  opacity: 0.4;
}

$tab-search__theme: (
  light: (
    --background-color: $white-100,
    --color: $grey-90,
  ),
  dark: (
    --background-color: $dark-awesome-bar-background,
    --color: $white-100,
  ),
);

.tab-search {
  flex: 1;
  padding: 4px 0 4px 4px;
  position: relative;

  &__input {
    @extend %text-body-10;
    width: 100%;
    height: 30px;
    padding-left: 28px;
    border: 1px solid $grey-90-a30;
    border-radius: 4px;

    &::-moz-placeholder {
      @extend %text-body-10;
    }
  }

  &__label:hover &__input {
    border-color: $grey-90-a50;
  }

  &__icon {
    @extend %tab-search__icon;
    left: 11px;
  }

  &__clear-icon {
    @extend %tab-search__icon;
    @extend %slow-transition;
    transition-property: opacity;
    right: 8px;
    cursor: pointer;
  }

  &__input:placeholder-shown + &__clear-icon {
    display: none;
    opacity: 0;
  }
}

@each $theme, $colors in $tab-search__theme {
  .tab-search {
    &--theme-#{$theme} &__input {
      background-color: map-get( $colors, --background-color );
      color: map-get( $colors, --color );
      border: 1px solid rgba( map-get( $colors, --color ), 0.3 );

      &::-moz-placeholder {
        color: map-get( $colors, --color );
      }
    }

    &--theme-#{$theme} &__label:hover &__input {
      border-color: rgba( map-get( $colors, --color ), 0.5 );
    }

    &--theme-#{$theme} &__icon {
      fill: map-get( $colors, --color );
    }

    &--theme-#{$theme} &__clear-icon {
      fill: map-get( $colors, --color );
    }
  }

  @media (prefers-color-scheme: $theme) {
    .tab-search {
      &__input {
        background-color: map-get( $colors, --background-color );
        color: map-get( $colors, --color );
        border: 1px solid rgba( map-get( $colors, --color ), 0.3 );

        &::-moz-placeholder {
          color: map-get( $colors, --color );
        }
      }

      &__label:hover &__input {
        border-color: rgba( map-get( $colors, --color ), 0.5 );
      }

      &__icon {
        fill: map-get( $colors, --color );
      }

      &__clear-icon {
        fill: map-get( $colors, --color );
      }
    }
  }
}
</style>

// src/components/TabSearch.svelte
<script>
  export let theme

  import {
    getWindow,
  } from "../store/helpers.mjs"
  import {
    bem,
    debounce,
    onStateChange,
  } from "./helpers.mjs"

  let search_text = ""
  let search_resolved = true
  let window_id = window.current_window_id
  let search_history = []

  const __MSG_tab_search_placeholder__ = window.background.getMessage( "tab_search_placeholder" )

  onStateChange( state => {
    const state_window = getWindow( state, window_id )
    if( state_window && state_window.search != null ) {
      const index = search_history.indexOf( state_window.search.text )
      if( index > -1 ) {
        search_history.splice( index, 1 )
      } else {
        search_text = state_window.search.text
      }
      search_resolved = state_window.search.resolved
    } else {
      search_text = ""
      search_resolved = true
    }
  })

  function onUpdateSearchText() {
    console.info('runSearch', search_text)
    search_history.push( search_text )
    window.background.runTabSearch( window.store, window_id, search_text )
  }

  function clearSearchText() {
    console.info('clearSearchText', search_text)
    search_text = ""
    window.background.runTabSearch( window.store, window_id, search_text )
  }
</script>

<style lang="sass">
  @import "../styles/photon";

  $dark-awesome-bar-background: #474749;

  %tab-search__icon {
    position: absolute;
    top: 11px;
    height: 16px;
    width: 16px;
    opacity: 0.4;
  }

  $tab-search__theme: (
    light: (
      --background-color: $white-100,
      --color: $grey-90,
    ),
    dark: (
      --background-color: $dark-awesome-bar-background,
      --color: $white-100,
    ),
  );

  .tab-search {
    flex: 1;
    padding: 4px 0 4px 4px;
    position: relative;

    &__input {
      @extend %text-body-10;
      width: 100%;
      height: 30px;
      padding-left: 28px;
      border: 1px solid $grey-90-a30;
      border-radius: 4px;

      &::-moz-placeholder {
        @extend %text-body-10;
      }
    }

    &__label:hover &__input {
      border-color: $grey-90-a50;
    }

    &__icon {
      @extend %tab-search__icon;
      left: 11px;
    }

    &__clear-icon {
      @extend %tab-search__icon;
      @extend %slow-transition;
      transition-property: opacity;
      right: 8px;
      cursor: pointer;
    }

    &__input:placeholder-shown + &__clear-icon {
      display: none;
      opacity: 0;
    }
  }

  @each $theme, $colors in $tab-search__theme {
    .tab-search {
      &--theme-#{$theme} &__input {
        background-color: map-get( $colors, --background-color );
        color: map-get( $colors, --color );
        border: 1px solid rgba( map-get( $colors, --color ), 0.3 );

        &::-moz-placeholder {
          color: map-get( $colors, --color );
        }
      }

      &--theme-#{$theme} &__label:hover &__input {
        border-color: rgba( map-get( $colors, --color ), 0.5 );
      }

      &--theme-#{$theme} &__icon {
        fill: map-get( $colors, --color );
      }

      &--theme-#{$theme} &__clear-icon {
        fill: map-get( $colors, --color );
      }
    }
  }
</style>

<div class="{ bem( `tab-search`, { theme } ).join( ' ' ) }">
  <label class="tab-search__label">
    <svg class="tab-search__icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
      <path d="M15.707 14.293l-4.822-4.822a6.019 6.019 0 1 0-1.414 1.414l4.822 4.822a1 1 0 0 0 1.414-1.414zM6 10a4 4 0 1 1 4-4 4 4 0 0 1-4 4z"></path>
    </svg>
    <input class="tab-search__input" type="search" bind:value={ search_text } on:input={ e => onUpdateSearchText() } placeholder={ __MSG_tab_search_placeholder__ }/>
    <svg class="tab-search__clear-icon" on:click="{ e => clearSearchText() }" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M6.586 8l-2.293 2.293a1 1 0 0 0 1.414 1.414L8 9.414l2.293 2.293a1 1 0 0 0 1.414-1.414L9.414 8l2.293-2.293a1 1 0 1 0-1.414-1.414L8 6.586 5.707 4.293a1 1 0 0 0-1.414 1.414L6.586 8zM8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0z"></path>
    </svg>
  </label>
</div>
